spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shorten_link_db
    username: 
    password: 
    
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update    show-sql: true
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    
  application:
    name: shorten-link-service

server:
  port: 8080